site_name: GDUT ACM Wiki
site_url: https://wiki.gdutacm.com/
site_description: 广东工业大学 ACM 集训队 Wiki
repo_url: https://github.com/GDUT-ACM/gdut-acm-wiki/
edit_uri: tree/main/docs

theme:
  name: material
  font:
    code: JetBrains Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
